// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctondxwcblonedkfpijg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0b25keHdjYmxvbmVka2ZwaWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDU3OTMsImV4cCI6MjA2NTU4MTc5M30.39A683-lkoGR8wpvY2wxq0ZhvYwXwyAo4J7BMPnplCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);